---
apiVersion: v1
kind: Service
metadata:
  name: details
  namespace: {{.Values.global.prefix}}-backends
  labels:
    app: details
    service: details
spec:
  ports:
  - port: {{.Values.global.details.port}}
    name: http
  selector:
    app: details
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-details
  namespace: {{.Values.global.prefix}}-backends
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v1
  namespace: {{.Values.global.prefix}}-backends
  labels:
    app: details
    version: v1
spec:
  replicas: {{.Values.global.details.replicas}}
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      serviceAccountName: bookinfo-details
      containers:
      - name: details
        image: 'docker.io/istio/examples-bookinfo-details-v1:{{.Values.global.details.imageTag}}'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{.Values.global.details.port}}
